### ISSUE TITLE
.note可以用什么软件打开啊

### ISSUE THREAD

**Issue by mizhewei** [sleepq123/Reptile_YouDaoNote#1]
.note可以用什么软件打开啊

**Comment by sleepq123** [comment]
感谢star! .note文件需要把文件后缀名改成doc.   因为在有道云笔记里其实就是doc文件的

**Comment by wow-lc** [comment]
感谢star! .note文件需要把文件后缀名改成doc.   因为在有道云笔记里其实就是doc文件的
