### ISSUE TITLE
使用报错了

### ISSUE THREAD

**Issue by LuckyCenter** [sleepq123/Reptile_YouDaoNote#4]
![image](https://user-images.githubusercontent.com/50699965/134617496-a557b2e8-e934-419e-a34c-0b7b9e9ee8f4.png)

**Comment by wow-lc** [comment]
执行npm run build后可以尝试这样再试试 （**确保已经登录有道云网页版**）
![image](https://user-images.githubusercontent.com/31381291/136535477-f9f682bd-6b5b-4a1f-ba9c-6089b4cf49b6.png)
